title: "Héroes de América"
description: "Memorias de la independencia americana · Est. MDCCCXVII"
baseurl: "/Bautista-Cevasco"
url: "https://BautiCev.github.io"
theme: minima
author: "Archivo Histórico"
lang: es

markdown: kramdown
permalink: /:categories/:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
